name: EnhancedEconomy
version: '0.11.1A'
main: it.italiandudes.enhancedeconomy.EnhancedEconomy
api-version: 1.19
commands:
  enhancedeconomy:
    description: The plugin command.
    usage: /<command>
    aliases: [ee]